# Generated by Django 5.2.6 on 2025-11-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name="Culture's name")),
            ],
            options={
                'verbose_name': 'Culture',
                'verbose_name_plural': 'Cultures',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name="Disease's name")),
                ('type', models.CharField(default='OTHER', max_length=10, verbose_name="Disease's type")),
                ('cultures', models.ManyToManyField(related_name='diseases', to='agro_catalog.culture', verbose_name='Impressive cultures')),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name="Drug's name")),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price (grn)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('fights_diseases', models.ManyToManyField(related_name='drugs', to='agro_catalog.disease', verbose_name='Fights diseases')),
            ],
            options={
                'verbose_name': 'Drug',
                'verbose_name_plural': 'Drugs',
                'ordering': ['name'],
            },
        ),
    ]
